services:
  petalpal:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: petalpal-app

    ports:
      - "3000:3000"

    env_file:
      - .env

    restart: unless-stopped